### ISSUE TITLE
[core] FE BE AI 병합

### ISSUE THREAD

**Issue by pjhcsols** [pjhcsols/VirtualFitting_System#60]
https://github.com/pjhcsols/VirtualFitting_System/pull/55
https://github.com/pjhcsols/VirtualFitting_System/pull/56
https://github.com/pjhcsols/VirtualFitting_System/pull/57
https://github.com/pjhcsols/VirtualFitting_System/pull/58
https://github.com/pjhcsols/VirtualFitting_System/pull/59

**Comment by KimGona** [comment]
1. FAST API, OOTDiffusion 모델을 사용하여 가상착장 서비스 제공
- 프론트엔드에서 가상착장 서비스를 요청하면 user Image와 cloth 이미지 url을 받아 이미지 2장을 다운로드 받음.
- 다운로드받은 이미지 2장을 이용해서 가상착장 이미지를 생성함.
- 생성된 가상착장 이미지를 프론트엔드로 넘겨주고, 프론트에서 잘 받았다는 확인메시지를 받으면 
 AI 서버의 로컬 스토리지에서 해당 userid의 user 이미지, cloth 이미지, 가상착장 이미지를 모두 삭제해줌

2. 사용자 친화적인 서비스 제공
- 기존의 가상착장 모델은 input 이미지의 가로: 세로 비율이 정해져 있음.(가로3: 세로4)
- 사진에서 객체가 차지하는 비율이 작으면 성능이 좋지 않음 (input이미지에 따라 성능의 편차가 심함)
-> yolo8 모델을 이용하여 user 이미지, cloth 이미지 둘 다 중심 객체를 detection함.
그리고 중심 객체가 포함되도록 알맞은 비율로 crop한 뒤에 전처리된 이미지들을 사용하여 일관성 있게 좋은 성능을 사용자에게 제공하고자 함.
